### ISSUE TITLE
two population pipeline

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/analysis#25]
I wanted to open some more discussion on our goals for the two population snakemake pipeline. Is our desire to have both fastsimcoal and dadi in the same snakefile so that users would run both as default? And do we want to run it only on humans or do we want to do the two population drosophila model as well? Currently the dadi pipeline is set up for humans only.

**Comment by andrewkern** [comment]
yes we would want to run two population models on both humans and flies. it would be great if you could add fastsimcoal to the existing workflow for humans and then begin building out the second species.

@jgallowa07 generalized the n_t workflow I believe to handle alternative models. is that work done now @jgallowa07? would be a good example to look at.

**Comment by jgallowa07** [comment]
>  Is our desire to have both `fastsimcoal` and `dadi` in the same `snakefile` so that users would run both as default? 
I think a target rule for each program separately is nice (Mostly for sanity checks and debugging) - but my opinion is that the default `all` target should be running both programs. The most important part is that the programs run on the _same_ resulting data from the simulation runs. This is because the analysis should represent a direct comparison of the two programs. 
> And do we want to run it only on humans or do we want to do the two population drosophila model as well? Currently the dadi pipeline is set up for humans only
Ideally, It would be nice to generalize this to run _all_ stdpopsim models.

**Comment by jgallowa07** [comment]
> I wanted to open some more discussion on our goals for the two population snakemake pipeline. Is our desire to have both fastsimcoal and dadi in the same snakefile so that users would run both as default? And do we want to run it only on humans or do we want to do the two population drosophila model as well? Currently the dadi pipeline is set up for humans only.

I think a target rule for each program separately is nice (Mostly for sanity checks and debugging) - but my opinion is that the default `all` target should be running both programs. The most important part is that the programs run on the _same_ resulting data from the simulation runs. This is because the analysis should represent a direct comparison of the two programs. 

Ideally, It would be nice to generalize this to run _all_ stdpopsim models.

**Comment by andrewkern** [comment]
yes that would be the goal. at this point I think we should split the two population task, from the n_t task, but I could imagine having a snakefile that sits above that hierarchy and runs the whole thing.

**Comment by jgallowa07** [comment]
In my opinions, a "Master" Snakefile would be nice, but not a necessity. Especially because the `n_t` and `two pop` have different goals, the simulation for the two can be run separately. Also, given our time constraint, it may be slightly complex to generalize this across the two scenarios in a sensible way (for things like sampling, reps, plotting). 

On another note, @ckyriazis I'm happy to do a review on what you have now and try to make some helpful suggestions.

**Comment by ckyriazis** [comment]
Thanks for the input - all this sounds good. I've been making progress with the fsc pipeline and think it should be relatively straightforward to bring it together with the dadi pipeline, I can follow up with you on that next week once Ive made a bit more progress. One area where I could use input right now, though, is I havent actually been able to get the dadi pipeline to run in entirety - its spitting out an "unrecognized selector sent to instance" error during the fit_dadi_model rule. Have you been able to run it @jgallowa07 or have any insight into that error?

**Comment by jgallowa07** [comment]
I haven't run it yet or know what that error means off the top of my head, but I'm happy to take a look next week. It may prove useful to put them in the same `Snakefile` now, and simply create a target rule for each so that you don't need to integrate them later.

**Comment by ckyriazis** [comment]
Ok yea, thats what I'm working on right now. I'll just leave the dadi stuff aside for now.

**Comment by andrewkern** [comment]
@ckyriazis do you want to open a PR so we can help you along? @jgallowa07's PR refactoring the snakemake stuff is now merged

**Comment by ckyriazis** [comment]
Yes! Just about to do this.

**Comment by jgallowa07** [comment]
Should we close this? seems like this is all addressed in #29

**Comment by andrewkern** [comment]
closing
