### ISSUE TITLE
Generation times as an attribute of model class

### ISSUE THREAD

**Issue by jradrion** [popgensims/analysis#32]
Andy and I noticed that generation times might be better implemented as a class attribute for each of the models. Currently these times are hard-coded into some of the models, however they are provided to some of the n_t analysis programs as user-specified arguments, leading to potential misspecification issues.

**Comment by andrewkern** [comment]
yes-- @jeromekelleher @jgallowa07 can you see any reason that we wouldn't have `generation_time` as a class variable associated with each demographic model that we implement?

**Comment by jeromekelleher** [comment]
In principle it's a property of the species though, isn't it? I think @jgallowa07 added this to stdpopsim a while back (sorry, travelling at the moment).

**Comment by andrewkern** [comment]
right now `generation_time` seems to be set under the three human models, but not for drosophila or arabidopsis. I can fix that and submit a PR.

Also `generation_time` is currently redefined on the analysis side, in the config file that @jgallowa07 set up. We should instead set that within the Snakefile so that we can pull the value of `generation_time` directly from the stdpopsim module.

**Comment by jradrion** [comment]
This has now been implemented on the analysis side!

**Comment by jeromekelleher** [comment]
Sounds like this is wrapped up, so closing.
